name: bpmn_application
description: Clean architecture contracts and usecases layer for BPMN application.
version: 0.0.1
repository: https://github.com/staylorx/bpmn_application
publish_to: none

environment:
  sdk: ">3.11.0 <4.0.0"

dependencies:
  bpmn_domain:
    git:
      url: https://github.com/staylorx/bpmn_domain
      ref: main
  equatable: ^2.0.8
  fpdart: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
  shouldly: ^0.5.0+1
